services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/Warsaw
    volumes:
      - /volume1/docker/duplicati/config:/config:rw
      - /volume1/docker/duplicati/backups:/backups:rw
      - /volume1/docker:/source:rw
      - /volume1/backup:/backup:rw
    ports:
      - 8200:8200
    restart: on-failure:10
