version: '3.7'
services:
  watchtower:
    image: containrrr/watchtower
    command: --cleanup --schedule "0 0 5 * * *" # use cron or --interval 300
    restart: on-failure:5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
