version: '3.9'
services:
    portainer-ce:
        ports:
            - 8000:8000
            - 9443:9443
        container_name: portainer
        environment:
          PUID: 0
          PGID: 0
          TZ: Europe/Warsaw
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume1/docker/portainer/portainer_data:/data
        image: portainer/portainer-ce:latest
